global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: http_services
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'host.docker.internal:8080'
        labels:
          application: 'demo-service'
